### ISSUE TITLE
Demonstrate how to create a Ubuntu deb package with OpenCV3

### ISSUE THREAD

**Issue by chutsu** [wavelab/libwave#106]
At current our travis takes 20 minutes+ to install opencv, we need a faster way to install libwave dependencies. 1 solution is to install big dependencies like OpenCV3 as a Ubuntu debian package, this issue demonstrates how one can create such a package.

**Comment by archielee** [comment]
At the moment, why does it take 15 minutes to complete the installation?

**Comment by archielee** [comment]
So I found this link:
https://unix.stackexchange.com/questions/46122/how-can-i-create-a-deb-package-with-my-compiled-opencv-build

It looks like you can already create debs without any special packaging. It requires a small change (cloning from source and checking out tags/3.2.0). The CMake flags can be manually set in CMakeCache.txt

**Comment by archielee** [comment]
note: it could just be as simple as adding a line in the install script:

```
    cmake \
        -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D WITH_TBB=ON \
        -D WITH_V4L=ON \
        -D WITH_QT=ON \
        -D WITH_OPENGL=ON \
        -D CPACK_BINARY_DEB=ON ..
```

and running `make package -j$(nproc)`

It should generate 3 debs: lib, dev, python

**Comment by archielee** [comment]
If we want to use a PPA, we cannot upload .deb packages directly. They must be built on Launchpad. A guide is here:
https://askubuntu.com/questions/71199/manually-created-deb-how-do-i-upload-to-a-ppa

**Comment by archielee** [comment]
I uploaded a test package onto my personal PPA, it's currently processing but you can test with that. I'm also going to push what I have onto the branch. I'll write up a small README to explain how to build it

**Comment by archielee** [comment]
Made an initial commit on the branch but it's huge. There's a readme in scripts/install/opencv3/debian

**Comment by leokoppel** [comment]
Cool, nice work @archielee 

Just checking, we will not keep it in this repo right? It is not really the place for 160MB of opencv.

**Comment by chutsu** [comment]
No, I just reminded him to remove the debs.

**Comment by archielee** [comment]
I won't be around next week but will likely have internet access. Let me know if you need me to remove anything else
