### ISSUE TITLE
Refactor header files to be more consistent

### ISSUE THREAD

**Issue by chutsu** [wavelab/libwave#128]
At current we have small variations of commenting header file defines, for example some end the header file with

```
/** @} end of group */
}  // namespace wave

#endif  // WAVE_CONTAINERS_MEASUREMENT_HPP
```
vs 

```
/** @} end of group */
}  // end of wave namespace
#endif
```

**Comment by leokoppel** [comment]
Just throwing it out there, have you considered `#pragma once`?
