### ISSUE TITLE
Add diagnostic tools to the front end

### ISSUE THREAD

**Issue by navganti** [wavelab/libwave#181]
Add tools for diagnostics to the front end:

- [x] Feature track lengths

- [ ] Outliers rejected from RANSAC 

- [ ] Information on feature warping

and more!

**Comment by chutsu** [comment]
Ha, I found a typo in your issue title - fixed

**Comment by navganti** [comment]
thanks @chutsu :smile:

**Comment by navganti** [comment]
After a discussion with @arunxdas, these diagnostic tools will be moved to the `libwave_apps` repository. It  makes sense to directly integrate these tools with ROS for the two main lab projects.
