### ISSUE TITLE
TicToc test sometimes fails (wave_utils)

### ISSUE THREAD

**Issue by navganti** [wavelab/libwave#209]
#### Platform
Travis

#### Steps to Reproduce
1. Build something.

#### Expected result
It passes.

#### Observed result
The tictoc test within wave_utils fails, but only sometimes...

**Comment by navganti** [comment]
@chutsu did you fix this? I've been waiting 4 years

**Comment by chutsu** [comment]
*Chris has left the chat

**Comment by navganti** [comment]
Me waiting for a fix ☹️ 

![image](https://user-images.githubusercontent.com/19216792/149607024-a7034786-2b70-42d8-8d98-952eb5496e03.png)
