### ISSUE TITLE
Add kindr as an external dependency.  

### ISSUE THREAD

**Issue by arunxdas** [wavelab/libwave#25]
Need to add the kindr library as part of deps.  Either from source or using the package manager.  See https://github.com/ethz-asl/kindr for install instructions

**Comment by chutsu** [comment]
Can you not do this within your PR #24 ?

**Comment by arunxdas** [comment]
Currently stuck on travis-build errors.  Kindr not finding Eigen3 using the install script

**Comment by chutsu** [comment]
Should we close this issue, I think this should be resolved along with your PR #24.

**Comment by arunxdas** [comment]
Will be resolved with PR #24.
