### ISSUE TITLE
Modify combined state formulation for wave_gtsam.

### ISSUE THREAD

**Issue by navganti** [wavelab/libwave#275]
In order to decouple scan matches and the constant velocity model, the states need to change from

Pose_ODOM_BL
Vel_ODOM_BL
GPS_BIAS 

to

T_ODOM_BL
T_MAP_ODOM
Vel_ODOM_BL

and an additional 
T_ECEF_MAP

The GPS, Lidar, and propagation residuals need to be reformulated for this new state, and the initialization inside the localizer needs to be updated to reflect this new state. In effect, this change is implementing REP-105 for frame conventions. It should move any jitters in the output due to scan matches to T_MAP_ODOM to ensure that the motion model smoothness is only enforced on the sequence of T_ODOM_BL.

**Comment by Jebediah** [comment]
Per our meeting yesterday, the new states should be
T_ODOM_BL
T_MAP_ODOM
BL_V_ODOM_BL
T_Eprime_E  (translation only)
