### ISSUE TITLE
segfault bug in ground segmentation

### ISSUE THREAD

**Issue by mpitropov** [wavelab/libwave#287]
This issue has been confirmed

#### Platform
Ubuntu 16.04
master branch

#### Steps to Reproduce
1. Start up the moose
2. catkin build occupancy --cmake-args -DCMAKE_BUILD_TYPE=Debug
3. run occ grid with gdb
4. I ran a whole loop of colby at one point. Bu then another time I ran it, it crashed after running for maybe 10 seconds.
4. look at bt when it crashes.

I'm going to try to find a bag with this issue but I haven't seen it on my local bags.

#### Expected result
No crashes
#### Observed result
Crashes
#### Possible cause
segfault as listed in gdb image
#### Related issues
None that I know of.

![image](https://user-images.githubusercontent.com/3324075/42585070-35ba84c0-8524-11e8-87e6-34dacff550af.png)

https://github.com/wavelab/libwave/blob/8d77107d967f7d7d44d5191c8f77732a549a92ee/wave_matching/include/wave/matching/impl/ground_segmentation.hpp#L64

**Comment by mpitropov** [comment]
![image](https://user-images.githubusercontent.com/3324075/42698871-ac592d80-86ae-11e8-97a2-a61b60dc812d.png)

**Comment by carloswanguw** [comment]
you can do that?
