### ISSUE TITLE
SLAM Reading list update

### ISSUE THREAD

**Issue by stevenwaslander** [wavelab/libwave#36]
This issue was opened to add in further updates to the SLAM reading list for everyone in the SLAM group.  The changes to be added include: Expanded list of great papers.

**Comment by chutsu** [comment]
Is this linked to any branch?

**Comment by stevenwaslander** [comment]
I haven't made any changes yet, but have a local branch I started, that's it.

**Comment by stevenwaslander** [comment]
Nevermind, we already did it with #37 .
