### ISSUE TITLE
VTK install script does not work in Ubuntu 16.04 

### ISSUE THREAD

**Issue by chutsu** [wavelab/libwave#40]
The current vtk install script does not work in ubunt 16.04, please modify it a little so that it recognizes what version the user is using. You use the [`ceres_install.bash` ](https://github.com/wavelab/libwave/blob/master/scripts/install/ceres_install.bash) as an example. Note that we can install  libpcl 1.7 in Ubuntu 16.04 via `apt-get` is that good enough?

**Comment by leokoppel** [comment]
What is the VTK install script? Where do we use VTK?

**Comment by chutsu** [comment]
PCL
