### ISSUE TITLE
Properly find dependencies with CMake

### ISSUE THREAD

**Issue by leokoppel** [wavelab/libwave#45]
The purpose of CMake is to allow cross-platform builds without making assumptions about directory structure.

Over time some absolute paths have crept into CMakeLists files. Conversely, some dependencies are found by virtue of being in the default path, but are never declared. These practices may cause problems for users with different directory structures, different OS, multiple versions of libraries installed, etc.

The tasks for this issue are:

#### Remove hardcoded paths from CMake files
   This includes lines such as
   ```cmake
   INCLUDE_DIRECTORIES(/usr/include/eigen3)
   ```
   and 
   ```cmake
   INCLUDE_DIRECTORIES(/usr/include)
   ```

#### Explicitly list all dependencies
   For example, Boost is not listed

**Comment by leokoppel** [comment]
In case its useful, here are my slides on where `find_package` looks for things: https://docs.google.com/presentation/d/1zyuT8qPTHDNuhl5jSF2-NTLZ8PPnuNF0VHDxaFFHuPM/edit?usp=sharing

**Comment by jitrc** [comment]
Yes and I use this for Eigen
```
find_package(Eigen3 QUIET)
if(NOT EIGEN3_FOUND)
  # Fallback to cmake_modules
  find_package(cmake_modules REQUIRED)
  find_package(Eigen REQUIRED)
  set(EIGEN3_INCLUDE_DIRS ${EIGEN_INCLUDE_DIRS})
  set(EIGEN3_LIBRARIES ${EIGEN_LIBRARIES})  # Not strictly necessary as Eigen is head only
  # Possibly map additional variables to the EIGEN3_ prefix.
else()
  set(EIGEN3_INCLUDE_DIRS ${EIGEN3_INCLUDE_DIR})
endif()
```

**Comment by chutsu** [comment]
Sure go ahead, there are already 2 (Kindr and Eigen cmake `Find` files in the `libwave/cmake` dir), but fully agree on listing all dependencies

**Comment by chutsu** [comment]
Consensus has been made, we should use cmake files to find dependencies, closing this now but should create new issues for independent issues for each new cmake dependency config file, e.g. PCL, Ceres.

**Comment by leokoppel** [comment]
This issue is a bit broad but it's pretty common to have an overarching issue which is mentioned in sub-issues or multiple PRs. I see it as still open.

Note the issue description says nothing about the creation of "cmake dependency config files". That is not inherent to the issue.

> leokoppel added a commit that referenced this issue 9 hours ago

Oh, that repetitive github referencing is ugly. I did not know it prints the message every time I rebase a commit!

**Comment by chutsu** [comment]
ok, keeping it open.
