### ISSUE TITLE
Automate code listings in documentation

### ISSUE THREAD

**Issue by leokoppel** [wavelab/libwave#47]
Our documentation (see [api_template](https://github.com/wavelab/libwave/blob/master/docs/api/api_template.md)) includes code listings (class definitions, function prototypes, etc). These blocks of code should be automatically generated from the header files, otherwise maintaining the docs is a lot of work (and they will quickly become out of date).

The solution should 
~- be compatible with current ditto system?~
- support Latex, ideally with Mathjax (not image) output

A common solution is [Doxygen](http://www.stack.nl/~dimitri/doxygen/), but will have to investigate whether it works as desired.

(An alternative is to _not_ include code listings in the documentation, and just write "here's a quick example of how to use this class, see header.hpp for the full API".)

**Comment by chutsu** [comment]
I feel like this discussion needs the attention of others, we need to decide this as a team.
