### ISSUE TITLE
OpenCV FAST Detector Wrapper

### ISSUE THREAD

**Issue by navganti** [wavelab/libwave#65]
The goal of this issue is to wrap OpenCV's FAST Detector. This will focus on a general detector interface, which should aid future detector implementation.

This is the start of the development for the front end for vision based (VO/VIO) SLAM using libwave.

**Comment by chutsu** [comment]
I've done that a while ago: https://github.com/chutsu/yarl/blob/master/src/vision/fast.cpp

What you may want to focus instead is a generic front end interface, for example given an image, how would you write the front end "classes" to easily switch between different features (be it Good, Fast, FREAK, etc...) and how would the feature correspondence look like?

**Comment by navganti** [comment]
@chutsu sounds good. I started the exception stuff; I'll start migrating your yarl code into libwave then and rename the issue.

**Comment by navganti** [comment]
@chutsu, yarl is released under GPLv3. I'm not sure what kind of license we want for libwave, but this could lead to some problems. To avoid these problems maybe I should write our own, and not rely on other code...?

tagging @michaelhsmart @leokoppel @arunxdas to also chime in on this.

**Comment by chutsu** [comment]
yarl is mine, you can do whatever you want.

**Comment by navganti** [comment]
Haha I figured you wouldn't sue us. @michaelhsmart mentioned it was more of a concern with regards to our industry partners, and the work we do with them.

**Comment by leokoppel** [comment]
Good point. The idea is to copy parts of the code into this library, right, not include it as a dependency? Then it would fall under this license. Chris is allowed to re-license his own code.

But it does get complicated. For example, if a partner runs some kind of IP analysis on the code, it may flag Chris' other library as a plagiarized source. I don't know if that's a problem.

**Comment by michaelhsmart** [comment]
Do we have a private location for this discussion? Our internal licensing issues should not be on public issues :)

**Comment by navganti** [comment]
To Basecamp we go!
