### ISSUE TITLE
Modify install_deps to install OpenCV3

### ISSUE THREAD

**Issue by navganti** [wavelab/libwave#68]
Currently installation script installs OpenCV2.4. 

Decision as per discussion here: https://public.3.basecamp.com/p/3uFf3ZrDSChhjESrMj8Lh4vq

**Comment by chutsu** [comment]
I know we discussed it in basecamp, but I'm not sure code related things should be discussed in basecamp and linked from issue to basecamp. Image this, if we used something else other than basecamp the discussion details will be losted.

**Comment by navganti** [comment]
Good point @chutsu. Figured since Basecamp is our main "discussion" hub it's where we should chat about it. I didn't want to create a Github Issue without first discussing the concern with the group, especially since this could affect quite a bit of people, and isn't just a code specific. 

I guess in the future I'll create the Github Issue, any discussion could be had here, and THEN the issue link can be posted in Basecamp/Slack so everyone on the project sees it with some visibility.

**Comment by chutsu** [comment]
Fix in #69
