### ISSUE TITLE
Travis cache fails

### ISSUE THREAD

**Issue by leokoppel** [wavelab/libwave#76]
Travis is printing:
```
found cache
adding /usr/local/src to cache
running `casher add/usr/local/src` took longer than 180 seconds and has been aborted
```

As a result, ceres and opencv build are still really slow.

Unknown whether the cache is actually so big that it takes >180s, or whether it simply hangs for some other reason.

Related: #14

**Comment by chutsu** [comment]
culprit is during caching, it takes too long for travis to add `/usr/local/src` to cache

![screenshot_2017-05-23_22-57-55](https://cloud.githubusercontent.com/assets/91460/26385124/668a9590-400b-11e7-854f-0089625e554a.png)

**Comment by leokoppel** [comment]
Yes, that's the output I pasted in the issue description : )

**Comment by leokoppel** [comment]
Travis cache is not relevant now that we have a better solution, PPAs. See #106 #132
